### ISSUE TITLE
Gestión de proyectos de software

### ISSUE THREAD

**Issue by antoniio** [SistemasTecTlaxiaco/infografia-antoniio-1#2]
[Infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-antoniio-1/files/7117507/Infografia.pdf)

**Comment by Joel343** [comment]
20
1.- Hace falta referencias

**Comment by josealfredo79** [comment]
Bien hecho y revisado, faltan metodologías, herramientas
